### ISSUE TITLE
请问本项目数据库怎么处理的

### ISSUE THREAD

**Issue by YangQii** [ltaoo/books_server_python#1]
请问这个项目数据库怎么处理的，用的什么数据库，本地怎么搭建

**Comment by ltaoo** [comment]
这个项目使用 docker-compose 搭建 python 环境和 postgresql 数据库环境，按照 README 就可以完成搭建。

- 1、构建镜像
- 2、启动容器

启动容器后，就会运行两个 docker 容器并且相互通信，代码实际是跑在 python 容器中的。
如果按照上面的步骤有问题，可以在这里反馈。
